import Head from "next/head";
import Searchinput from "../components/Searchinput";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex max-w-7xl items-center align-center justify-center">
          <div className="justify-center">
            <button>Start game</button>
          </div>
          <div className="pt-10">
            <Searchinput />
          </div>
        </div>
      </main>
    </div>
  );
}
